//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workout_Application_Tracker
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class LowerBody : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LowerBody()
        {
            this.WorkoutTables = new HashSet<WorkoutTable>();
        }

        private decimal lowerBodyID;
        private string _lowerBody;

        public decimal LowerBodyID { get => lowerBodyID; set{
                lowerBodyID = value;
                OnPropertyChanged(nameof(LowerBodyID));
            }
        }
        public string LowerBody1 { get => _lowerBody; set {
                _lowerBody = value;
                OnPropertyChanged(nameof(LowerBody1));
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutTable> WorkoutTables { get; set; }



        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
