//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workout_Application_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkoutTable
    {
        public decimal WorkoutID { get; set; }
        public Nullable<decimal> UpperBodyID { get; set; }
        public string Sets___Reps1 { get; set; }
        public decimal Weight1 { get; set; }
        public Nullable<decimal> LowerBodyID { get; set; }
        public string Sets___Reps2 { get; set; }
        public decimal Weight2 { get; set; }
        public Nullable<decimal> AbsID { get; set; }
        public string Sets___Reps_3 { get; set; }
        public Nullable<decimal> Weight_3 { get; set; }
    
        public virtual Ab Ab { get; set; }
        public virtual LowerBody LowerBody { get; set; }
        public virtual UpperBody UpperBody { get; set; }
    }
}
